PROJECT := p0

# Define the Python interpreter to use
PYTHON := python3

# Target to run the main script
runpy: $(PROJECT).py
	@echo Running $(PROJECT).py
	$(PYTHON) $(PROJECT).py

runlisp:

rungo:

runrust:

runerlang:

runj:

runk:

run: runpy runlisp rungo runrust runerlang runj runk # j k/q/kdb

# A phony target is used when a rule does not produce a file named after the target
.PHONY: run
